//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public int ID { get; set; }
        public string MaNV { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<bool> ngay1 { get; set; }
        public Nullable<bool> ngay2 { get; set; }
        public Nullable<bool> ngay3 { get; set; }
        public Nullable<bool> ngay4 { get; set; }
        public Nullable<bool> ngay5 { get; set; }
        public Nullable<bool> ngay6 { get; set; }
        public Nullable<bool> ngay7 { get; set; }
        public Nullable<bool> ngay8 { get; set; }
        public Nullable<bool> ngay9 { get; set; }
        public Nullable<bool> ngay10 { get; set; }
        public Nullable<bool> ngay11 { get; set; }
        public Nullable<bool> ngay12 { get; set; }
        public Nullable<bool> ngay13 { get; set; }
        public Nullable<bool> ngay14 { get; set; }
        public Nullable<bool> ngay15 { get; set; }
        public Nullable<bool> ngay16 { get; set; }
        public Nullable<bool> ngay17 { get; set; }
        public Nullable<bool> ngay18 { get; set; }
        public Nullable<bool> ngay19 { get; set; }
        public Nullable<bool> ngay20 { get; set; }
        public Nullable<bool> ngay21 { get; set; }
        public Nullable<bool> ngay22 { get; set; }
        public Nullable<bool> ngay23 { get; set; }
        public Nullable<bool> ngay24 { get; set; }
        public Nullable<bool> ngay25 { get; set; }
        public Nullable<bool> ngay26 { get; set; }
        public Nullable<bool> ngay27 { get; set; }
        public Nullable<bool> ngay28 { get; set; }
        public Nullable<bool> ngay29 { get; set; }
        public Nullable<bool> ngay30 { get; set; }
        public Nullable<bool> ngay31 { get; set; }
    }
}
